apiVersion: v1
kind: Service
metadata:
  name: ci-cd-python-app
  labels:
    app: ci-cd-python-app
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: ci-cd-python-app
  type: ClusterIP

